version: "0.0.1"
services:

  main_server:
    build: .
    ports:
      - "10071:10071"
      - "10075:10075"
      - "10077:10077"
      - "10078:10078"
      - "10073:10073"
      - "50000:50000/udp"
      - "10070:10070/udp"
    depends_on:
      - "db"

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ../horizon-server-database/data:/var/opt/mssql/data
      - ../horizon-server-database/log:/var/opt/mssql/log
      - ../horizon-server-database/secrets:/var/opt/mssql/secrets
